### ISSUE TITLE
Tuning auto drive constants, this is not necessary but could probably cut 0.5-0.25 seconds off our cycle. 

### ISSUE THREAD

**Issue by twisterjafla** [FRC-1799/2024-comp-bot-code#48]
the current auto drive works fine but could be speeded up with better tuning.

How the constants work for tuning purposes

Kp: is how aggressive the pid is, you want it to go faster increase this, however if its too high the system will overshoot
Ki: controls how much the system tries harder if its current efforts aren't working. be very careful with this, its really easy to get a robot that hits stuff because its ki is to big 
Kd limits the system so it doesn't overshoot. shouldn't be 0 but needs to be low. if it is too high the system will stop before it hits the point and exhibit jumping behaviors.

The current tune works fine but since the new robot is more responsive the final turn could be more aggressive. Additionally, the drive steps could be a lot more aggressive since MJ stops faster than Milkman by a decent amount.

**Comment by ThePrinterFRC1799** [comment]
tuned and works
